### ISSUE TITLE
用户注册邮件SMTP服务在哪修改？

### ISSUE THREAD

**Issue by feiruyun** [cube-ai/cubeai#4]
用户注册邮件SMTP服务在哪修改？是在文件
~/cubeai/uaa/src/main/resources/config/application-dev.yml
~/cubeai/uaa/src/main/resources/config/application-prod.yml
中的：
```
    mail:
        host: ***
        port: ***
        username: ***
        password: ***
        properties:
            mail:
                smtp:
                    auth: true
```
我只把***修改成自己的后，不好使，不知道是不是修改这四个地方？
谢谢！
